ContentManagementSystem/ContentManagementSystem.UI/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using ContentManagementSystem.BLL.Contracts;
using ContentManagementSystem.BLL.NinjectBindings;
using Ninject;

namespace ContentManagementSystem.UI.Controllers
{
    public class PageController : Controller
    {
        private readonly IStaticPageManager _staticPageManager;

        public PageController()
        {
            var kernel = new StandardKernel(new BllBindings());
            kernel.Load(Assembly.GetExecutingAssembly());
            _staticPageManager = kernel.Get<IStaticPageManager>();
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var r = _staticPageManager.GetAll();

            if (!r.Success)
            {
                SetErrorViewData(r.Message);
            }

            ViewData["StaticPages"] = r.Data.Where(sp => sp.IsLive).ToList();
        }

        private void SetErrorViewData(string message)
        {
            ViewData["Alert"] = "alert-danger";
            ViewData["Message"] = message;
        }
        // GET: StaticPage
        public ActionResult Index(int id)
        {
            var r = _staticPageManager.GetById(id);

            if(!r.Success)
                SetErrorViewData(r.Message);
            return View(r.Data);
        }
    }
}

ContentManagementSystem/ContentManagementSystem.UI/Views/Shared/_AddPostModal.cshtml
<!-- Start Add Post Modal -->
<div class="modal fade modal-wide" id="addPostModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel" align="center">Add Blog Post</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form id="addPostForm">
                        <div class="form-group" align="center">
                            <label>Title</label>
                            <input type="text" id="title" name="title" class="form-control"/>
                        </div>
                        <hr/>
                        <div class="form-group">
                            <label>Content</label>
                            <textarea id="content"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Tags : </label>
                            @*<div data-tags-input-name="tag" id="tagBox"></div>;*@
                            <input type="text" name="tags" id="tags" class="form-control"/>
                            <button type="button" id="tagButton">Add Tag</button>
                        </div>
                        <div class="form-group">
                            <label>Category</label>
                            <select id="selectCategory" name="selectCategory">
                                <option></option>
                            </select>
                            <button type="button" id="categoryButton">Add Category</button>
                        </div>
                        <div class="form-group">
                            <label>Expire Date</label>
                            @*<div id="expireDate"><input type="date" name="expireDate" id="expireDate"></div>*@
                            <input type="text" id="expireDate" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Publish Date</label>
                            @*<div id="publishDate"><input type="date" name="publishDate" id="publishDate"></div>*@
                            <input type="text" id="publishDate" name="publishDate" class="form-control">
                        </div>
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="form-group">
                                <label>Status</label>
                                <select id="statuses" name="statuses">
                                    <option></option>
                                </select>
                            </div>
                        }
                    </form>
                </div>
                <div class="row">
                    <div class="form-group">
                        Tags: <span class="tagList" id="showTags"></span>
                    </div>
                    <div class="form-group">
                        Categories : <span class="categoryList" id="showCategories"></span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                @if (User.IsInRole("Admin"))
                {
                    <button type="button" id="savePost" class="btn btn-primary">Add Post</button>
                    <button type="button" id="saveEditPost" class="btn btn-primary">Edit Post</button>
                }
                else
                {
                    <button type="button" id="submitApproval" class="btn btn-primary">Submit for Approval</button>
                    <button type="button" id="submitEditApproval" class="btn btn-primary">Submit Edit Approval</button>
                    <button type="button" id="saveDraft" class="btn btn-primary">Save as Draft</button>
                }
            </div>
        </div>
    </div>
</div>
<!-- End Add Post Modal -->

ContentManagementSystem/ContentManagementSystem.UI/Views/Shared/_CategoryModal.cshtml
<!-- Start Category Modal -->
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Category</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form id="addCategory">
                        <div class="form-group">
                            <label>Category Name</label>
                            <input type="text" id="catName" class="form-control" />
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="saveCategory" class="btn btn-primary">Add Category</button>
            </div>
        </div>
    </div>
</div>
<!-- End Category Modal -->

ContentManagementSystem/ContentManagementSystem.UI/Views/Shared/_Layout.cshtml
@using ContentManagementSystem.Model
@{
    var staticPages = (List<StaticPage>)ViewData["StaticPages"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href='https://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="loading" style="display: none;">
        Loading
        <i class="fa fa-spinner fa-spin" id="indicator"></i>
    </div>*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("C T E", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@*@Html.ActionLink("About", "About", "Home")*@</li>
                    @foreach (StaticPage sp in staticPages)
                    {
                        <li>@Html.ActionLink(sp.Title, "Index", "Page", new { id = sp.Id }, null)</li>
                    }
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (!string.IsNullOrEmpty(ViewData["Alert"]?.ToString()))
        {
            <div class="row" id="alert">
                <div class="col-xs-12 alert @ViewData["Alert"]">
                    <a href="#" class="close" data-dismiss="alert">&times;</a>@ViewData["Message"]
                </div>
            </div>
        }
        @RenderBody()
        <div class="clearfix visible-xs visible-sm visible-md visible-lg"></div>
        <footer>
            <br/>
            <div class="footer-left"><span class="leftSpan">&copy; Developed and Supported By JIST @DateTime.Now.Year</span></div>
            <div class="footer-right">@if ((string)ViewContext.RouteData.Values["controller"] != "Account" && (string)ViewContext.RouteData.Values["action"] != "Login")
            {
                <span class="rightSpan">@Html.Partial("_LoginPartial")</span>
            }</div>
        </footer>


        @*<div class="col-xs-12" id="footer">*@
            
           
        </div>
    @*</div>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/jquery.faloading-0.1.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="~/Scripts/app/uriVariables.js"></script>
    <script src="~/Scripts/jquery.dotdotdot.js"></script>

   @*<script type="text/javascript">

    $(document).ajaxSend(function (event, request, settings) {
        $('#loading').show();
    });


    $(document).ajaxComplete(function (event, request, settings) {
        $('#loading').hide();
    });
</script>*@

    <link rel="stylesheet" href="~/Content/jquery.faloading.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    @*<script>
    $(document).on('click', 'a', function() {
        $('body').faLoading();
    })
    </script>*@
</body>
</html>

ContentManagementSystem/ContentManagementSystem.UI/Views/Shared/_StaticPageModal.cshtml
<!-- Start Static Page Modal -->
<div class="modal fade" id="staticPageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Static Page</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form id="addStaticPage">
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" id="spTitle" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Content</label>
                            <textarea id="spMCEcontent" class="form-control" rows="5"></textarea>
                        </div>
                        <div class="form-group">
                            <label><input type="checkbox" id="spIsLive" />Page is live.</label>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="saveStaticPage" class="btn btn-primary">Add Static Page</button>
                <button type="button" id="saveEditStaticPage" class="btn btn-primary">Edit Static Page</button>
            </div>
        </div>
    </div>
</div>
<!-- End Static Page Modal -->